name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v3
        with:
          version: 11
          runtime: node@26
          cache: true

      - name: Build
        run: pn build

      - name: Lint
        run: pn lint

      - name: Test
        run: pn test

      - name: Publish to npmjs
        run: pn publish --provenance --access public

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v3
        with:
          version: 11
          runtime: node@26
          cache: true

      - name: Build
        run: pn build

      - name: Lint
        run: pn lint

      - name: Test
        run: pn test

      - name: Make the Package Scoped
        run: jq --arg scopedName "@${{ github.repository }}" '.name = $scopedName' package.json > tmp.json && mv tmp.json package.json

      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com/" >> ~/.npmrc

      - name: Publish to GitHub Packages Registry
        run: pn publish --no-git-checks
