name: Publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v3
        with:
          version: 11
          runtime: node@26
          cache: true

      - name: Build
        run: pn build

      - name: Lint
        run: pn lint

      - name: Test
        run: pn test

      - name: Format
        run: pn format:check

      - name: Publish to npmjs
        run: pnpm publish --provenance --access public

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v3
        with:
          version: 11
          runtime: node@26
          cache: true

      - name: Build
        run: pn build

      - name: Lint
        run: pn lint

      - name: Test
        run: pn test

      - name: Format
        run: pn format:check

      - name: make package scoped
        run: npx -y change-package-name @${{ github.repository }}

      - name: Publish to GitHub Packages registry
        run: pnpm publish --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
